---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
  namespace: kafka-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-broker
  template:
    metadata:
      labels:
        app: kafka-broker
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.5.0
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "SASL_PLAINTEXT://kafka-broker:9092"
        - name: KAFKA_LISTENERS
          value: "SASL_PLAINTEXT://:9092"
        - name: KAFKA_SECURITY_INTER_BROKER_PROTOCOL
          value: "SASL_PLAINTEXT"
        - name: KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL
          value: "PLAIN"
        - name: KAFKA_SASL_ENABLED_MECHANISMS
          value: "PLAIN"
        - name: KAFKA_OPTS
          value: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_jaas.conf -Dzookeeper.sasl.client=false" 
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND
          value: "true"
        volumeMounts:
        - name: jaas-config
          mountPath: /etc/kafka/secrets
          readOnly: true
      volumes:
      - name: jaas-config
        secret:
          secretName: kafka-jaas

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: kafka-monitoring
spec:
  ports:
  - port: 9092
    targetPort: 9092
  selector:
    app: kafka-broker
